### ISSUE TITLE
感情パラメータの実装

### ISSUE THREAD

**Issue by ikafurai19706** [Theme-Research-org/kadai_kenkyu-#26]
## 概要
- VOICEVOXで喋れるようにする
- 会話履歴を端末別に残す (ここまで #24 の続き)
- キャラ進化分岐・喋り中モーション選択に利用する感情パラメータを実装する
## 詳細
会話内容に応じて、**喜び**[joy]、**期待**[anticipation]、**怒り**[anger]、**嫌悪**[disgust]、**悲しみ**[sadness]、**驚き**[suprise]、**恐れ**[fear]、**信頼**[trust]の8パラメータ（プルチックの「感情の輪」）で感情を定義する。このパラメータはキャラクターの表情・動きに反映され、進化時までのパラメータ出現率によって進化先が分岐する。
## 方法
- VOICEVOX API( https://voicevox.su-shiki.com/su-shikiapis/ )で喋らせる
- 履歴はDynamoDBでなんとかする
- gpt-4oのjsonモードを併用し、パラメータとテキストを分けて出力させ、Unityに読ませる
- プロンプトは頑張っていい感じのを作る

**Comment by ikafurai19706** [comment]
#25 が完了次第InProgressに移行

**Comment by suzuuuuu09** [comment]
こうしたほうがトークンをちょっとだけ節約できるかも。
```diff
- "emotion": {
-     "joy": <int, min=0, max=9>,
-     "trust": <int, min=0, max=9>,
-     "fear": <int, min=0, max=9>,
-     "anger": <int, min=0, max=9>,
-     "sadness": <int, min=0, max=9>,
-     "disgust": <int, min=0, max=9>,
-     "surprise": <int, min=0, max=9>,
-     "vigilance": <int, min=0, max=9>
- },
- "text": <string>
+ "emotion": {
+     "joy": <int,range(0,9)>,
+     "trust": <int,range(0,9)>,
+     "fear": <int,range(0,9)>,
+     "anger": <int,range(0,9)>,
+     "sadness": <int,range(0,9)>,
+     "disgust": <int,range(0,9)>,
+     "surprise": <int,range(0,9)>,
+     "vigilance": <int,range(0,9)>
+ },
+ "text": <string>
```
あと、故意的に感情パラメーターを増減させることができたからそこだけどうにか対策したほうがよさそう。
